[phases.setup]
cmds = [
    "dotnet restore"
]

[phases.build]
cmds = [
    "dotnet publish -c Release -o ./publish"
]

[phases.install]
cmds = [
    "cp -r ./publish/* /app/"
]

[start]
cmd = "dotnet IntroductionToBlazer.dll"
